### ISSUE TITLE
Migration failing with an 'ImportError''

### ISSUE THREAD

**Issue by Larkhis** [taigaio/taiga-contrib-letschat#10]
Hi,
When i run python manage.py migrate taiga_contrib_letschat I get the error below:
`ImportError: cannot import name 'IsProjectAdmin'`
For info, i use a vagrant image of taiga.io.
Thanks, for your help.
Regards,
@Larkhis

**Comment by bameda** [comment]
This problem is because you are using an incompatible version of the plugin. `IsProjectAdmin` is in taiga-back 2.0.0 and you are using an older version

**Comment by bameda** [comment]
Yo have to use the release you need

```
> cd taiga-contrib-letschat
> git tag -l                                                                    master
0.0.1
0.0.2
0.0.4
1.10
1.9.1
2.0.0
```
