### ISSUE TITLE
API to post messages endpoint and auth token

### ISSUE THREAD

**Issue by rawlingsj** [taigaio/taiga-contrib-letschat#2]
First off this is awesome and I know it's only a couple of weeks old but I've got the lets chat plugin working with minimal effort so really nice work!

Is there already an API exposed to post the messages endpoint and auth token to the lets chat plugin?

i.e. something along the lines of

```
curl -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer ${AUTH_TOKEN}" \
  -d '{
          "messages_endpint": "http://localhost/rooms/123456789/messages",
          "auth_token": "12345678"
      }' \

  http://localhost:8000/api/v1/letschat
```

**Comment by bameda** [comment]
Try with 

```
curl -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer ${AUTH_TOKEN}" \
  -d '{
          "project": 123,
          "url": "http://localhost/rooms/123456789/messages",
          "token": "12345678"
      }' \

  http://localhost:8000/api/v1/letschat
```

But we have to make documentation about that

**Comment by rawlingsj** [comment]
Works perfectly - thanks!

**Comment by bameda** [comment]
you welcome :smiley_cat:

**Comment by astagi** [comment]
I'll add some docs during the weekend :smiley:

**Comment by bameda** [comment]
@astagi maybe the documentation of taiga-contrib-slack can serve as an example

**Comment by astagi** [comment]
@bameda yes, I started from taiga-contrib-slack for hipchat plugin as well :) we could think about a script to auto generate boilerplate code for plugins :)
