### ISSUE TITLE
Filtering messages to be sent to the chatroom

### ISSUE THREAD

**Issue by Goodnix** [taigaio/taiga-contrib-letschat#4]
Hi!
It will be great to be able to choose what events will be reported to the chatroom.

**Comment by superalex** [comment]
Good idea @Goodnix ! :+1:

**Comment by astagi** [comment]
Yeah it would reduce the amount of messages in the chatroom. I'll work on a general solution that could be integrated in each plugin. Thanks @Goodnix

**Comment by Kickball** [comment]
Any updates on this?

**Comment by astagi** [comment]
hi @Kickball sorry I have some work on a local branch for hipchat plugin... I forgot this task, I think to finish that before the end of July and port the same code on letschat plugin, sorry for my late :)

**Comment by astagi** [comment]
@Kickball @Goodnix @superalex I'm implementing configurable notifications on HipChat, then I'll port the code on Letschat https://github.com/taigaio/taiga-contrib-hipchat/pull/15

**Comment by superalex** [comment]
Great! :)

**Comment by astagi** [comment]
https://github.com/taigaio/taiga-contrib-letschat/pull/7

**Comment by astagi** [comment]
@Kickball @Goodnix @superalex #7 now merged into master ;) closing..
