### ISSUE TITLE
Access Chat Room

### ISSUE THREAD

**Issue by basingh-qasource** [taigaio/taiga-contrib-letschat#6]
Hi,

After following all steps described in taiga-contrib-letschat 'README' i am stuck with issues. 
Neither I can find any new table in taiga-back admin panel nor i can see any link to access chat room or anything related to taiga-contrib-letschat in taiga-front.
Please let me know where i am going wrong.

Thanks,
Balwinder

**Comment by bameda** [comment]
Hi Balwinder

This plugin is to send notifications when something change in Taiga to an
external lets chat server. So this plugin only add an admin panel to
configure it in /project/<your_projects>/admin/contrib/letschat like this:

[image: Inline image 1]

Can you see this panel?

## Regards

   _David Barragán Merino_
- Engineer *
  david.barragan@kaleidos.net
  david.barragan@kaleidos.net  | Tel: (+34) 913562995
  www.kaleidos.net/FFF8E7

**Comment by astagi** [comment]
@basingh-qasource any update?
